[package]
name = "zed_terraform"
version = "0.1.2"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/terraform.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
